steps:
#add any number of build steps to your build config file by including 
#additional name fields and pointing them to cloud builders (gcr.io/cloud-builders/) example docker builder.

#Set up and run npm tests
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/react-test'
  - '-f'
  - './client/Dockerfile.dev' 
  - './client'

- name: 'gcr.io/cloud-builders/npm'
  args:
  - 'install'

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'run'
  - '-t'
  - 'gcr.io/$PROJECT_ID/react-test'
  - 'npm'
  - 'run'
  - 'test'
  - '--'
  - '--coverage'

# Uses the docker builder (container image running docker) to build an image called my-image
#The args field of a step takes a list of arguments and passes them to the builder referenced by the name field.
#the command name (build)
#Docker tag (t)
#the name of the image to be built (gcr.io/my-project/my-image)
#the location of the source code (., meaning that the source code is present at the current working directory).
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/multi-client-cb:$REVISION_ID'
  - './client'

- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/multi-client-cb:latest'
  - './client'

#how to run gcloud build commands
# - name: "gcr.io/cloud-builders/gcloud"
#   args: ["app", "deploy"]


#push image
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'push'
  - 'gcr.io/$PROJECT_ID/multi-client-cb:$REVISION_ID'

- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'push'
  - 'gcr.io/$PROJECT_ID/multi-client-cb:latest'

#apply k8 manifests 
- name: 'gcr.io/cloud-builders/kubectl'
  args: 
  - 'apply'
  - '-f'
  - 'k8s'

#set image 
- name: 'gcr.io/cloud-builders/kubectl'
  args: 
  - 'set'
  - 'image'
  - 'deployments/client-deployment'
  - 'client=gcr.io/williamscj-gke-demos/multi-client-cb:$REVISION_ID'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=williamscj-gke-demos'

# multi-client-cb is pushed to Container Registry
images:
- 'gcr.io/$PROJECT_ID/multi-client-cb:$REVISION_ID'
- 'gcr.io/$PROJECT_ID/multi-client-cb:latest'

# Uses the ubuntu build step:
# to run a shell script; and
# set env variables for its execution
# - name: 'ubuntu'
#   args: ['bash', './deploy.sh']
#   env:
#   - 'SHA=$(git rev-parse HEAD)'